name: C CI - Windows (MSVC)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    # windows-2022 is required for MSVC
    runs-on: windows-2022

    steps:
      # Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Show runner info
      - name: Show runner info
        run: |
          systeminfo
          echo %PROCESSOR_ARCHITECTURE%

      # Normalize input file (remove BOM and enforce ASCII/CRLF line endings)
      # FIX: We use ASCII encoding on Out-File to strip any leading BOM characters
      # (like the mysterious '﻿' seen in the logs) and ensure clean line endings.
      - name: Normalize input file (Strip BOM)
        shell: powershell
        run: |
          # Read raw content, replace all newlines with Windows CRLF
          $content = (Get-Content -Path test\valid_inputs.txt -Raw) -replace "\r?\n", "`r`n"
          
          # Write back using ASCII encoding, which prevents the BOM
          $content | Out-File -FilePath test\valid_inputs.txt -Encoding ASCII

      # Build mainmat.exe using MSVC
      - name: Build mainmat.exe
        shell: cmd
        run: |
          REM Activate the Visual Studio build environment for x64 architecture.
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

          REM Compile all C sources into mainmat.exe
          cl /nologo /W4 /EHsc /std:c89 mainmat.c utils.c mymat.c

      # Run the program with sample input
      - name: Run mainmat.exe with sample input
        shell: cmd
        run: |
          if exist mainmat.exe (
            echo Running mainmat.exe with sample input
            echo Starting mainmat.exe with input redirection...
            mainmat.exe < test\valid_inputs.txt
          ) else (
            echo mainmat.exe not found
            dir
          )

      # Optional: Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mainmat-build
          path: |
            mainmat.exe
            *.obj